import os


DEFAULT_RESULT_ROOT = os.getenv("PROCLEAN_RESULT_ROOT", "results")
DEFAULT_FASTTEXT_MODEL_PATH = os.getenv("PROCLEAN_FASTTEXT_MODEL_PATH", "models/cc.en.300.bin")
DEFAULT_SEMANTIC_MODEL_PATH = os.getenv("PROCLEAN_SEMANTIC_MODEL_PATH", "models/qwen-0.6B")
DEFAULT_LLM_BASE_URL = os.getenv("PROCLEAN_LLM_BASE_URL", "")
DEFAULT_LLM_API_KEY = os.getenv("PROCLEAN_LLM_API_KEY", "")
DEFAULT_LLM_MODEL = os.getenv("PROCLEAN_LLM_MODEL", "")
